# Generated by Django 5.2.7 on 2025-11-03 23:55

import django.db.models.deletion
import filer.fields.file
import filer.fields.folder
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID задачи')),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('source_type', models.CharField(choices=[('LOCAL', 'Загрузить вручную'), ('YADISK', 'Из Яндекс.Диска')], default='LOCAL', help_text='Откуда загружаем файлы', max_length=20, verbose_name='Источник файлов')),
                ('task_type', models.CharField(choices=[('ONE_TIME', 'Одноразовый'), ('PERIODIC', 'Периодический')], default='ONE_TIME', help_text='Тип запуска задачи', max_length=20, verbose_name='Тип запуска задачи')),
                ('ya_disk_path', models.CharField(blank=True, help_text='Путь или ссылка на Яндекс.Диск, если выбран этот источник', max_length=1024, verbose_name='Ссылка на Яндекс.Диск')),
                ('interval', models.PositiveIntegerField(verbose_name='Интервал')),
                ('interval_type', models.CharField(choices=[('MINUTES', 'Минуты'), ('HOURS', 'Часы'), ('DAYS', 'Дни')], default='DAYS', max_length=10)),
                ('run_once_at', models.DateTimeField(blank=True, help_text='Если запуск один раз', null=True, verbose_name='Дата однократного запуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('PROCESSING', 'В обработке'), ('PROCESSING_FILLED_FILES', 'В обработке файлов из диска'), ('DONE', 'Обработан'), ('ERROR', 'Ошибка')], default='NEW', max_length=32, verbose_name='Статус')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('archive_after_send', models.BooleanField(default=True, verbose_name='Архивировать после отправки')),
                ('delete_after_send', models.BooleanField(default=False, verbose_name='Удалять после отправки')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('folder', filer.fields.folder.FilerFolderField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.folder', verbose_name='Папка в Filer')),
                ('result_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_result_file', to='filer.file', verbose_name='Файл с результатом')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('payload', models.JSONField(verbose_name='Данные выполнения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='transcriber.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'История задачи',
                'verbose_name_plural': 'История задач',
            },
        ),
    ]
