# Generated by Django 5.2.7 on 2025-11-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delete_after_send',
            field=models.BooleanField(default=True, verbose_name='Удалять после отправки'),
        ),
    ]
