# Generated by Django 5.2.7 on 2025-11-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0002_alter_task_delete_after_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='interval',
            field=models.PositiveIntegerField(default=0, verbose_name='Интервал'),
        ),
    ]
