# Generated by Django 5.2.7 on 2025-11-04 19:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0003_alter_task_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='run_once_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Если запуск один раз', verbose_name='Дата однократного запуска'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transcriber.task')),
            ],
            options={
                'verbose_name': 'Лог задачи',
                'verbose_name_plural': 'Логи задач',
                'ordering': ['-created_at'],
            },
        ),
    ]
