# Generated by Django 5.2.7 on 2025-11-07 16:12

import django.db.models.deletion
import filer.fields.file
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('transcriber', '0004_alter_task_run_once_at_tasklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_text', models.TextField(blank=True, verbose_name='Результат транскрипции')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('PROCESSING', 'В обработке'), ('DONE', 'Готов'), ('ERROR', 'Ошибка')], default='NEW', max_length=20, verbose_name='Статус')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filer_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file', verbose_name='Исходный файл')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='transcriber.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Файл задачи',
                'verbose_name_plural': 'Файлы задачи',
            },
        ),
    ]
